version: "3"
services:
  pigpiod:
    image: zinen2/alpine-pigpiod
    hostname: mrc_pigpiod
    container_name: mrc_pigpiod
    privileged: true
    ports:
      - "8888:8888"
    restart: always
  hardware:
   build:
       context: ./mrc-hardware
       dockerfile: Dockerfile.hardware
   container_name: mrc_hardware
   hostname: mrc_hardware
   privileged: true
   depends_on:
     - pigpiod
   command: python3 /hw/main.py
   restart: always
