version: '3'
services:
  mrc_sftp:
    image: 'registry.getcaas.io/library/sftp:0.0.1'
    command: 'mrcsftp:3ZYSxuJu6S:33'
    volumes:
      - 'mrc_back_media:/var/www/html/back/media'
      - 'mrc_back_db:/var/www/html/db'
    environment:
      - SSH_PROXY_USER=mrcsftp
      - SSH_REDIRECT_USER=mrcsftp
    networks:
      - mrc_network
      - proxy
  mrc_backend:
    image: 'registry.gitlab.com/maison-reconnectee/mrc/mrc_web_backend:0.33'
    labels:
      - client=mrc
      - backup=yes
    volumes:
      - 'mrc_back_db:/app/db'
      - 'mrc_back_static_0.33:/app/static'
      - 'mrc_back_media:/app/media'
    restart: always
    networks:
      - mrc_network
      - proxy
  mrc_frontend:
    image: 'registry.gitlab.com/maison-reconnectee/mrc/mrc_web_frontend:0.24'
    restart: always
    tty: true
    volumes:
      - 'mrc_front_dist_0.24:/app'
    networks:
      - mrc_network
      - proxy
  mrc_nginx:
    image: 'registry.gitlab.com/maison-reconnectee/mrc/mrc_web_nginx:0.8'
    volumes:
      - 'mrc_front_dist_0.24:/var/www/html/front/dist'
      - 'mrc_back_static_0.33:/var/www/html/back/static'
      - 'mrc_back_media:/var/www/html/back/media'
    restart: always
    depends_on:
      - mrc_backend
      - mrc_frontend
    networks:
      - mrc_network
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - 'traefik.http.routers.mrc_nginx.rule=Host(`app.lamaisonreconnectee.fr`, `back.lamaisonreconnectee.fr`)'
        - traefik.http.routers.mrc_nginx.entrypoints=web
        - traefik.http.services.mrc_nginx.loadbalancer.server.port=80
        - 'traefik.http.routers.mrc_nginx-secured.rule=Host(`app.lamaisonreconnectee.fr`, `app.lamaisonreconnectee.fr`)'
        - traefik.http.routers.mrc_nginx-secured.entrypoints=web-secured
        - traefik.http.routers.mrc_nginx-secured.tls.certresolver=mytlschallenge
        - traefik.http.middlewares.mrc_nginx-redirectscheme.redirectscheme.scheme=https
        - traefik.http.middlewares.mrc_nginx-redirectscheme.redirectscheme.permanent=true
        - traefik.http.routers.mrc_nginx.middlewares=test-redirectscheme@docker
networks:
  mrc_network: null
  proxy:
    external: true
volumes:
  mrc_back_db: null
  mrc_back_static_0.33: null
  mrc_back_media: null
  mrc_front_dist_0.24: null
