version: '3'
services:
  mrc_printer:
    build:
      context: ./mrc-hardware
      dockerfile: Dockerfile.printer
    container_name: mrc_printer
    hostname: mrc_printer
    environment:
      - MQTT_HOST=10.3.141.1
      - PRINTER_VENDOR_ID=1fc9
      - PRINTER_PRODUCT_ID=2016
    privileged: true
    command: python3 /printer/printer.py
    restart: always
  mrc_frontend:
    build:
      context: ./mrc-frontend
    container_name: mrc_frontend
    hostname: mrc_frontend
    restart: always
    volumes:
      - front_dist_b2:/app
  mrc_backend:
    build:
      context: ./mrc-backend
    container_name: mrc_backend
    hostname: mrc_backend
    volumes:
      - ./mrc-backend/db:/app/db
      - back_static:/app/static
      - back_media:/app/media
    ports:
      - '8080:8080'
    restart: always
  mrc_nginx:
    image: fholzer/nginx-brotli
    container_name: mrc_nginx
    hostname: mrc_nginx

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.django.conf:/etc/nginx/conf.d/django.conf
      - ./nginx.angular.conf:/etc/nginx/conf.d/angular.conf
      - front_dist_b2:/var/www/html/front/dist
      - back_static:/var/www/html/back/static
      - back_media:/var/www/html/back/media
    ports:
      - '80:80'
      - '8000:8000'
    restart: always
volumes:
  front_dist_b2: null
  back_static: null
  back_media: null
