version: '3'
services:
  mrc_printer:
    image: mrc_printer:latest
    container_name: mrc_printer
    hostname: mrc_printer
    environment:
      - MQTT_HOST=10.3.141.1
      - PRINTER_VENDOR_ID=1fc9
      - PRINTER_PRODUCT_ID=2016
    privileged: true
    command: python3 /printer/printer.py
    restart: always
  mrc_frontend:
    image: mrc_frontend:latest
    container_name: mrc_frontend
    hostname: mrc_frontend
    restart: always
    tty: true
    volumes:
      - front_dist_b13:/app
  mrc_backend:
    image: mrc_backend:latest
    container_name: mrc_backend
    hostname: mrc_backend
    volumes:
      - ./mrc-backend/db:/app/db
      - back_static_b13:/app/static
      - back_media:/app/media
    ports:
      - '8000:8000'
    restart: always
  mrc_nginx:
    image: mrc_nginx:latest
    container_name: mrc_nginx
    hostname: mrc_nginx
    volumes:
      - front_dist_b13:/var/www/html/front/dist
      - back_static_b13:/var/www/html/back/static
      - back_media:/var/www/html/back/media
    ports:
      - '80:80'
      - '8080:8080'
    restart: always
volumes:
  front_dist_b13: null
  back_static_b13: null
  back_media: null
