name: Images pour La Maison Reconnectée

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          git submodule set-url -- mrc-backend https://github.com/LaFabulerie/mrc-backend.git
          git submodule set-url -- mrc-frontend https://github.com/LaFabulerie/mrc-frontend.git
          git submodule init
          git submodule update
          docker build mrc-backend --build-arg="STAGE=web" -t mrc_backend
          docker build mrc-frontend --build-arg="STAGE=web" -t mrc_frontend
          docker build mrc-nginx --build-arg="STAGE=web" -t mrc_nginx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Tag Docker images with date
        run: |
          docker tag mrc_backend ghcr.io/${{ github.repository_owner }}/mrc_backend:$(date +%s)
          docker tag mrc_frontend ghcr.io/${{ github.repository_owner }}/mrc_frontend:$(date +%s)
          docker tag mrc_nginx ghcr.io/${{ github.repository_owner }}/mrc_nginx:$(date +%s)

      - name: Push Docker images to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mrc_backend:$(date +%s)
          docker push ghcr.io/${{ github.repository_owner }}/mrc_frontend:$(date +%s)
          docker push ghcr.io/${{ github.repository_owner }}/mrc_nginx:$(date +%s)
