name: Images pour La Maison Reconnectée
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Build Backend Docker image
      run: docker build mrc-backend --build-arg="STAGE=web" -t mrc_backend:$(date +%s)
    -
      name: Build Frontend Docker image
      run: docker build mrc-frontend --build-arg="STAGE=web" -t mrc_frontend:$(date +%s)
    -
      name: Build Nginx Docker image
      run: docker build mrc-nginx --build-arg="STAGE=web" -t mrc_nginx:$(date +%s)
