name: Images pour La Maison Reconnectée

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          git submodule set-url -- mrc-backend https://github.com/LaFabulerie/mrc-backend.git
          git submodule set-url -- mrc-frontend https://github.com/LaFabulerie/mrc-frontend.git
          git submodule init
          git submodule update
          docker build --no-cache mrc-backend --build-arg="STAGE=web" -t ghcr.io/${{ github.repository_owner }}/mrc_backend:$(date +'%d%m%Y')
          docker build --no-cache mrc-frontend --build-arg="STAGE=web" -t ghcr.io/${{ github.repository_owner }}/mrc_frontend:$(date +'%d%m%Y')
          docker build --no-cache mrc-nginx --build-arg="STAGE=web" -t ghcr.io/${{ github.repository_owner }}/mrc_nginx:$(date +'%d%m%Y')

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Push Docker images to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mrc_backend:$(date +'%d%m%Y')
          docker push ghcr.io/${{ github.repository_owner }}/mrc_frontend:$(date +'%d%m%Y')
          docker push ghcr.io/${{ github.repository_owner }}/mrc_nginx:$(date +'%d%m%Y')
  deploy_to_ovh:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: SSH into OVH VM and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io
            cd /home/debian/lamaisonreconnecte
            ./run.sh
