name: Images pour La Maison Reconnectée

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_to_ovh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get the latest commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: SSH into OVH VM and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io
            echo "$COMMIT_HASH"
            cd /home/debian/lamaisonreconnecte
            ./run.sh 
